"use client";

import { useEffect, useMemo, useState } from "react";
import { GoogleAuthProvider, createUserWithEmailAndPassword, onAuthStateChanged, signInWithEmailAndPassword, signInWithPopup, signOut, type User } from "firebase/auth";
import { doc, serverTimestamp, setDoc } from "firebase/firestore";
import { auth, db } from "@/lib/firebase";
import { flashcards, lessons, questions } from "@/data/math06";

type Screen = "home" | "learn" | "flash" | "practice" | "mastery";

export default function Home() {
  const [user,setUser]=useState<User|null>(null); const [loading,setLoading]=useState(true);
  const [screen,setScreen]=useState<Screen>("home"); const [qi,setQi]=useState(0); const [fi,setFi]=useState(0);
  const [flipped,setFlipped]=useState(false); const [selected,setSelected]=useState<number|null>(null); const [checked,setChecked]=useState(false);
  const [correct,setCorrect]=useState(0); const [attempts,setAttempts]=useState(0); const [weak,setWeak]=useState<Record<string,number>>({});
  useEffect(()=>onAuthStateChanged(auth,u=>{setUser(u);setLoading(false)}),[]);
  const q=questions[qi]; const mastery=attempts?Math.round(correct/attempts*100):0;
  const weakest=useMemo(()=>Object.entries(weak).sort((a,b)=>b[1]-a[1])[0]?.[0]||"No weakness detected yet",[weak]);
  async function saveProgress(nextCorrect:number,nextAttempts:number,nextWeak:Record<string,number>){if(!user)return;await setDoc(doc(db,"users",user.uid,"progress","MATH-06"),{moduleId:"MATH-06",correct:nextCorrect,attempts:nextAttempts,mastery:nextAttempts?Math.round(nextCorrect/nextAttempts*100):0,weakSkills:nextWeak,updatedAt:serverTimestamp()},{merge:true});}
  async function check(){if(selected===null||checked)return;setChecked(true);const ok=selected===q.answer;const nc=correct+(ok?1:0),na=attempts+1;const nw={...weak};if(!ok)nw[q.skill]=(nw[q.skill]||0)+1;setCorrect(nc);setAttempts(na);setWeak(nw);await saveProgress(nc,na,nw);}
  function next(){setSelected(null);setChecked(false);setQi((qi+1)%questions.length);}
  if(loading)return <main className="auth"><b>Loading FE Mission Dreams…</b></main>;
  if(!user)return <Auth />;
  return <main className="shell">
    <header className="topbar"><div className="brand">FE MISSION DREAMS</div><h1 className="title">MATH-06 · Triangle Trigonometry</h1><div className="sub">FE Mechanical · Learn → Practice → Repair → Master</div></header>
    <div className="tabs">{(["home","learn","flash","practice","mastery"] as Screen[]).map(x=><button key={x} className={`tab ${screen===x?"active":""}`} onClick={()=>setScreen(x)}>{x[0].toUpperCase()+x.slice(1)}</button>)}</div>
    <section className="content">
      {screen==="home"&&<><div className="card hero"><span className="pill">REFERENCE MODULE</span><h2>Build trig confidence for FE day.</h2><p className="sub">Short concept review, active recall, timed-style practice, and targeted repair when you miss a skill.</p><div className="statrow"><div className="stat"><b>{mastery}%</b>Mastery</div><div className="stat"><b>{attempts}</b>Attempts</div><div className="stat"><b>{correct}</b>Correct</div></div></div><div className="grid"><button className="action" onClick={()=>setScreen("learn")}><strong>📘 Learn</strong><span>Core formulas and decision rules</span></button><button className="action" onClick={()=>setScreen("flash")}><strong>⚡ Flashcards</strong><span>Fast formula recall</span></button><button className="action" onClick={()=>setScreen("practice")}><strong>🎯 Practice</strong><span>FE-style questions with diagnosis</span></button><button className="action" onClick={()=>setScreen("mastery")}><strong>📈 Mastery</strong><span>See progress and weak skills</span></button></div></>}
      {screen==="learn"&&<>{lessons.map((l,i)=><article className="card lesson" key={l.title}><span className="pill">LESSON {i+1}</span><h3>{l.title}</h3><p>{l.body}</p></article>)}<button className="primary" onClick={()=>setScreen("flash")}>Continue to flashcards</button></>}
      {screen==="flash"&&<><div className="card flash" onClick={()=>setFlipped(!flipped)}><span className="pill">CARD {fi+1} / {flashcards.length}</span>{!flipped?<><h2>{flashcards[fi].front}</h2><p className="note">Tap card to reveal</p></>:<><h2>{flashcards[fi].back}</h2><p>{flashcards[fi].note}</p></>}</div><button className="primary" onClick={()=>{setFi((fi+1)%flashcards.length);setFlipped(false)}}>Next card</button></>}
      {screen==="practice"&&<><div className="card"><div style={{display:"flex",justifyContent:"space-between",gap:8}}><span className="pill">{q.difficulty.toUpperCase()}</span><span className="note">{qi+1}/{questions.length} · {q.skill}</span></div><h2>{q.prompt}</h2>{q.choices.map((c,i)=>{let cl="choice";if(selected===i)cl+=" selected";if(checked&&i===q.answer)cl+=" correct";if(checked&&selected===i&&i!==q.answer)cl+=" wrong";return <button disabled={checked} className={cl} key={c} onClick={()=>setSelected(i)}><b>{String.fromCharCode(65+i)}.</b> {c}</button>})}{!checked?<button className="primary" disabled={selected===null} onClick={check}>Check answer</button>:<><div className={`feedback ${selected===q.answer?"good":"bad"}`}><b>{selected===q.answer?"Correct — skill strengthened":"Weakness detected: "+q.skill}</b><p>{q.explanation}</p>{selected!==q.answer&&<><b>Repair</b><p>{q.repair}</p><span className="note">Common trap: {q.trap}</span></>}</div><button className="primary" onClick={next}>Next question</button></>}</div></>}
      {screen==="mastery"&&<><div className="card"><span className="pill">MATH-06 MASTERY</span><h2>{mastery}%</h2><div className="progress"><div style={{width:`${mastery}%`}} /></div><p className="note">Based on {attempts} completed practice attempts.</p></div><div className="card"><h3>Priority repair</h3><p><b>{weakest}</b></p><p className="note">Incorrect answers are grouped by skill so the next version can automatically serve targeted repair questions.</p></div><button className="secondary" onClick={()=>signOut(auth)}>Sign out</button></>}
    </section>
    <nav className="bottom"><button className={screen==="home"?"active":""} onClick={()=>setScreen("home")}>Home</button><button className={screen==="learn"?"active":""} onClick={()=>setScreen("learn")}>Learn</button><button className={screen==="practice"?"active":""} onClick={()=>setScreen("practice")}>Practice</button><button className={screen==="mastery"?"active":""} onClick={()=>setScreen("mastery")}>Mastery</button></nav>
  </main>;
}

function Auth(){const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");async function run(mode:"login"|"signup"){try{setError("");if(mode==="signup")await createUserWithEmailAndPassword(auth,email,password);else await signInWithEmailAndPassword(auth,email,password)}catch(e){setError(e instanceof Error?e.message:"Authentication failed")}}async function google(){try{setError("");await signInWithPopup(auth,new GoogleAuthProvider())}catch(e){setError(e instanceof Error?e.message:"Google sign-in failed")}}return <main className="auth"><div className="authbox"><div className="brand">FE MISSION DREAMS</div><h1 className="title">Train smarter for the FE.</h1><p className="sub">Your first mission: MATH-06 Triangle Trigonometry.</p><div className="card"><input type="email" placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/>{error&&<p className="error">{error}</p>}<button className="primary" onClick={()=>run("login")}>Sign in</button><div style={{height:8}}/><button className="secondary" onClick={()=>run("signup")}>Create student account</button><div className="divider">or</div><button className="secondary" onClick={google}>Continue with Google</button></div></div></main>}
