"use client";

import { useEffect, useMemo, useState } from "react";
import { FirebaseError } from "firebase/app";
import { GoogleAuthProvider, createUserWithEmailAndPassword, onAuthStateChanged, sendPasswordResetEmail, signInWithEmailAndPassword, signInWithPopup, signOut, type User } from "firebase/auth";
import { doc, getDoc, serverTimestamp, setDoc } from "firebase/firestore";
import { auth, db } from "@/lib/firebase";
import { flashcards, lessons, questions } from "@/data/math06";
import { feMechanicalSubjects } from "@/data/fe-mechanical/subjects";

type ModuleScreen="home"|"learn"|"flash"|"practice"|"mastery";
type AppView="dashboard"|"subject"|"module";
type Progress={correct?:number;attempts?:number;weakSkills?:Record<string,number>};

export default function Home(){
 const[user,setUser]=useState<User|null>(null),[loading,setLoading]=useState(true);
 const[view,setView]=useState<AppView>("dashboard"),[subjectId,setSubjectId]=useState<string>("math"),[screen,setScreen]=useState<ModuleScreen>("home");
 const[qi,setQi]=useState(0),[fi,setFi]=useState(0),[flipped,setFlipped]=useState(false),[selected,setSelected]=useState<number|null>(null),[checked,setChecked]=useState(false);
 const[correct,setCorrect]=useState(0),[attempts,setAttempts]=useState(0),[weak,setWeak]=useState<Record<string,number>>({}),[saveError,setSaveError]=useState("");
 useEffect(()=>onAuthStateChanged(auth,async u=>{setUser(u);if(u){try{const snap=await getDoc(doc(db,"users",u.uid,"progress","MATH-06"));if(snap.exists()){const d=snap.data() as Progress;setCorrect(d.correct||0);setAttempts(d.attempts||0);setWeak(d.weakSkills||{})}}catch{setSaveError("Progress could not be loaded. You can still practice, but Firestore access should be checked.")}}else{setCorrect(0);setAttempts(0);setWeak({})}setLoading(false)}),[]);
 const q=questions[qi],mastery=attempts?Math.round(correct/attempts*100):0,subject=feMechanicalSubjects.find(s=>s.id===subjectId)||feMechanicalSubjects[0];
 const weakest=useMemo(()=>Object.entries(weak).sort((a,b)=>b[1]-a[1])[0]?.[0]||"No weakness detected yet",[weak]);
 async function saveProgress(nc:number,na:number,nw:Record<string,number>){if(!user)return;try{setSaveError("");await setDoc(doc(db,"users",user.uid,"progress","MATH-06"),{moduleId:"MATH-06",correct:nc,attempts:na,mastery:na?Math.round(nc/na*100):0,weakSkills:nw,updatedAt:serverTimestamp()},{merge:true})}catch{setSaveError("Your answer was recorded on this device, but progress could not be saved to Firestore.")}}
 async function check(){if(selected===null||checked)return;setChecked(true);const ok=selected===q.answer,nc=correct+(ok?1:0),na=attempts+1,nw={...weak};if(!ok)nw[q.skill]=(nw[q.skill]||0)+1;setCorrect(nc);setAttempts(na);setWeak(nw);await saveProgress(nc,na,nw)}
 function next(){setSelected(null);setChecked(false);setQi((qi+1)%questions.length)}
 function openSubject(id:string){setSubjectId(id);setView("subject")}
 function openMath06(){setScreen("home");setView("module")}
 if(loading)return <main className="auth"><b>Loading FE Mission Dreams…</b></main>;if(!user)return <Auth/>;

 if(view==="dashboard")return <main className="shell"><header className="topbar"><div className="brand">FE MISSION DREAMS</div><h1 className="title">FE Mechanical Student Dashboard</h1><div className="sub">All exam subjects · one account · desktop and mobile progress sync</div></header><section className="content"><div className="card hero"><span className="pill">FE MECHANICAL</span><h2>Your complete study mission</h2><p className="sub">Choose a subject. Every production section will follow Learn → Reference → Flashcards → Problems → Full Solutions → Diagnose → Repair → Retest → Mastery.</p><div className="statrow"><div className="stat"><b>{feMechanicalSubjects.length}</b>Subjects</div><div className="stat"><b>{mastery}%</b>MATH-06</div><div className="stat"><b>{attempts}</b>Attempts</div></div></div><div className="grid">{feMechanicalSubjects.map(s=><button key={s.id} className="action" onClick={()=>openSubject(s.id)}><strong>{String(s.order).padStart(2,"0")}. {s.title}</strong><span>{s.sections.length} sections · planned exam coverage {s.examQuestionRange[0]}–{s.examQuestionRange[1]} questions</span></button>)}</div><button className="secondary" onClick={()=>signOut(auth)}>Sign out</button></section></main>;

 if(view==="subject")return <main className="shell"><header className="topbar"><button className="linkbutton" onClick={()=>setView("dashboard")}>← All subjects</button><div className="brand">FE MISSION DREAMS</div><h1 className="title">{subject.title}</h1><div className="sub">FE Mechanical · {subject.sections.length} syllabus sections</div></header><section className="content"><div className="card"><span className="pill">SUBJECT MAP</span><h2>{subject.title}</h2><p className="sub">Open a section to study concepts, references, flashcards, FE-style problems, full solutions, repair, retest, and mastery.</p></div><div className="grid">{subject.sections.map(sec=>{const live=subject.id==="math"&&sec.id==="trigonometry";return <button key={sec.id} className="action" onClick={live?openMath06:undefined} disabled={!live}><strong>{sec.title}</strong><span>{live?"MATH-06 Triangle Trigonometry · Open production module":"Production content pipeline · section framework ready"}</span></button>})}</div><div className="card"><h3>Every section will contain</h3><p>Learn · Formula / Reference Review · Flashcards · FE-style Problems · Full Worked Solutions · Diagnose Mistake · Repair Problem · Retest · Mastery</p></div></section></main>;

 return <main className="shell"><header className="topbar"><button className="linkbutton" onClick={()=>{setSubjectId("math");setView("subject")}}>← Mathematics</button><div className="brand">FE MISSION DREAMS</div><h1 className="title">MATH-06 · Triangle Trigonometry</h1><div className="sub">Learn → Reference → Flashcards → Problems → Solution → Repair → Mastery</div></header><div className="tabs">{(["home","learn","flash","practice","mastery"] as ModuleScreen[]).map(x=><button key={x} className={`tab ${screen===x?"active":""}`} onClick={()=>setScreen(x)}>{x==="flash"?"Flashcards":x[0].toUpperCase()+x.slice(1)}</button>)}</div><section className="content">
 {saveError&&<div className="feedback bad"><b>Progress sync notice</b><p>{saveError}</p></div>}
 {screen==="home"&&<><div className="card hero"><span className="pill">MATH-06</span><h2>Triangle Trigonometry</h2><p className="sub">Concept review, formula recall, FE-style practice, complete worked solutions, and targeted repair.</p><div className="statrow"><div className="stat"><b>{mastery}%</b>Mastery</div><div className="stat"><b>{attempts}</b>Attempts</div><div className="stat"><b>{correct}</b>Correct</div></div></div><div className="grid"><button className="action" onClick={()=>setScreen("learn")}><strong>📘 Learn</strong><span>Core concepts and decision rules</span></button><button className="action" onClick={()=>setScreen("learn")}><strong>📐 Formula / Reference</strong><span>FE-ready trig relationships</span></button><button className="action" onClick={()=>setScreen("flash")}><strong>⚡ Flashcards</strong><span>Fast formula recall</span></button><button className="action" onClick={()=>setScreen("practice")}><strong>🎯 Problems + Solutions</strong><span>FE-style questions with full worked solutions</span></button><button className="action" onClick={()=>setScreen("mastery")}><strong>📈 Diagnose / Mastery</strong><span>Weak skills, repair, and progress</span></button></div></>}
 {screen==="learn"&&<>{lessons.map((l,i)=><article className="card lesson" key={l.title}><span className="pill">LESSON {i+1}</span><h3>{l.title}</h3><p>{l.body}</p></article>)}<div className="card"><span className="pill">FORMULA / REFERENCE REVIEW</span>{flashcards.map(f=><p key={f.front}><b>{f.front}:</b> {f.back} <span className="note">— {f.note}</span></p>)}</div><button className="primary" onClick={()=>setScreen("flash")}>Continue to flashcards</button></>}
 {screen==="flash"&&<><div className="card flash" onClick={()=>setFlipped(!flipped)}><span className="pill">CARD {fi+1} / {flashcards.length}</span>{!flipped?<><h2>{flashcards[fi].front}</h2><p className="note">Tap card to reveal</p></>:<><h2>{flashcards[fi].back}</h2><p>{flashcards[fi].note}</p></>}</div><button className="primary" onClick={()=>{setFi((fi+1)%flashcards.length);setFlipped(false)}}>Next card</button></>}
 {screen==="practice"&&<div className="card"><div style={{display:"flex",justifyContent:"space-between",gap:8}}><span className="pill">{q.difficulty.toUpperCase()}</span><span className="note">{qi+1}/{questions.length} · {q.skill}</span></div><h2>{q.prompt}</h2>{q.choices.map((c,i)=>{let cl="choice";if(selected===i)cl+=" selected";if(checked&&i===q.answer)cl+=" correct";if(checked&&selected===i&&i!==q.answer)cl+=" wrong";return <button disabled={checked} className={cl} key={c} onClick={()=>setSelected(i)}><b>{String.fromCharCode(65+i)}.</b> {c}</button>})}{!checked?<button className="primary" disabled={selected===null} onClick={check}>Check answer</button>:<><div className={`feedback ${selected===q.answer?"good":"bad"}`}><b>{selected===q.answer?"Correct — skill strengthened":"Diagnose: "+q.skill}</b><p>{q.explanation}</p></div><div className="feedback good"><b>Full worked solution</b>{q.solution.split("\n").map((line,i)=><p key={i} style={{margin:"8px 0"}}>{line}</p>)}</div>{selected!==q.answer&&<div className="feedback bad"><b>Repair this skill</b><p>{q.repair}</p><span className="note">Common trap: {q.trap}</span></div>}<button className="primary" onClick={next}>Next / Retest question</button></>}</div>}
 {screen==="mastery"&&<><div className="card"><span className="pill">MATH-06 MASTERY</span><h2>{mastery}%</h2><div className="progress"><div style={{width:`${mastery}%`}}/></div><p className="note">Based on {attempts} completed practice attempts.</p></div><div className="card"><h3>Priority repair</h3><p><b>{weakest}</b></p><p className="note">Incorrect answers are grouped by skill so repair and retest can target the weakest area.</p></div></>}
 </section><nav className="bottom"><button onClick={()=>setView("dashboard")}>Dashboard</button><button className={screen==="learn"?"active":""} onClick={()=>setScreen("learn")}>Learn</button><button className={screen==="practice"?"active":""} onClick={()=>setScreen("practice")}>Practice</button><button className={screen==="mastery"?"active":""} onClick={()=>setScreen("mastery")}>Mastery</button></nav></main>
}

function friendlyAuthError(e:unknown){if(!(e instanceof FirebaseError))return"Something went wrong. Please try again.";const m:Record<string,string>={"auth/invalid-email":"Please enter a valid email address.","auth/missing-password":"Please enter your password.","auth/weak-password":"Password must be at least 6 characters.","auth/email-already-in-use":"An account already exists with this email. Try signing in.","auth/invalid-credential":"Email or password is incorrect.","auth/user-not-found":"Email or password is incorrect.","auth/wrong-password":"Email or password is incorrect.","auth/popup-closed-by-user":"Google sign-in was canceled.","auth/popup-blocked":"Your browser blocked the Google sign-in window. Please allow pop-ups and try again.","auth/unauthorized-domain":"Google sign-in is not enabled for this website yet.","auth/too-many-requests":"Too many attempts. Please wait a few minutes and try again.","auth/network-request-failed":"We could not reach the sign-in service. Check your connection and try again."};return m[e.code]||"We could not sign you in. Please try again."}
function Auth(){const[email,setEmail]=useState(""),[password,setPassword]=useState(""),[error,setError]=useState(""),[notice,setNotice]=useState(""),[showPassword,setShowPassword]=useState(false),[busy,setBusy]=useState(false);function validate(mode:"login"|"signup"){const clean=email.trim();if(!clean)return"Please enter your email address.";if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(clean))return"Please enter a valid email address.";if(!password)return"Please enter your password.";if(mode==="signup"&&password.length<6)return"Password must be at least 6 characters.";return""}async function run(mode:"login"|"signup"){const v=validate(mode);if(v){setError(v);setNotice("");return}try{setBusy(true);setError("");setNotice("");if(mode==="signup")await createUserWithEmailAndPassword(auth,email.trim(),password);else await signInWithEmailAndPassword(auth,email.trim(),password)}catch(e){setError(friendlyAuthError(e))}finally{setBusy(false)}}async function google(){try{setBusy(true);setError("");await signInWithPopup(auth,new GoogleAuthProvider())}catch(e){setError(friendlyAuthError(e))}finally{setBusy(false)}}async function reset(){const clean=email.trim();if(!clean){setError("Enter your email address first, then tap Forgot password.");return}try{setBusy(true);setError("");await sendPasswordResetEmail(auth,clean);setNotice("Password reset email sent. Check your inbox.")}catch(e){setError(friendlyAuthError(e))}finally{setBusy(false)}}return <main className="auth"><div className="authbox"><div className="brand">FE MISSION DREAMS</div><h1 className="title">Train smarter for the FE.</h1><p className="sub">Complete FE Mechanical preparation for desktop and mobile.</p><div className="card"><label htmlFor="email" className="note">Email</label><input id="email" autoComplete="email" type="email" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)}/><label htmlFor="password" className="note">Password</label><input id="password" autoComplete="current-password" type={showPassword?"text":"password"} placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)}/><div style={{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",margin:"-4px 0 14px"}}><label className="note"><input type="checkbox" checked={showPassword} onChange={e=>setShowPassword(e.target.checked)} style={{width:"auto",marginRight:7}}/>Show password</label><button type="button" className="linkbutton" onClick={reset} disabled={busy}>Forgot password?</button></div>{error&&<p className="error" role="alert">{error}</p>}{notice&&<p className="success">{notice}</p>}<button className="primary" disabled={busy} onClick={()=>run("login")}>{busy?"Please wait…":"Sign in"}</button><div style={{height:8}}/><button className="secondary" disabled={busy} onClick={()=>run("signup")}>Create student account</button><div className="divider">or</div><button className="secondary" disabled={busy} onClick={google}>Continue with Google</button></div></div></main>}
